### ISSUE TITLE
Database Schema

### ISSUE THREAD

**Issue by ssoonmi** [AdamYLiang/toobU#2]
`videos`
- [x] A `video` should belong to a `channel` instead of `user` if you want to implement `channels`. A `video` will belong to a `user` through `channel`
---
`channels`
- [x] `name` of a `channel` should be unique, not just for a `user`
---
`subscriptions`
- nice uniqueness constraint!
---
`likes`
- [x] I would suggest making `likes` polymorphic if you choose to implement `likes` on `comments`/`playlists` in the future
---
`playlists`
- [x] typo on index on `[:title, :user_id], unique: true` (`author_id` instead of `user_id`)
---
`playlists_videos`
- [x] make the table `playlist_videos` instead of `playlists_videos` (I think this is by convention)
- [x] put an index on `playlist_id` and `video_id` separately below table

Awesome work!
If you don't think some of these suggestions are appropriate, please comment below!

**Comment by AdamYLiang** [comment]
Agreed with the suggestions! Changes are up.

**Comment by ssoonmi** [comment]
Nice!
