### ISSUE TITLE
Sample State

### ISSUE THREAD

**Issue by ssoonmi** [AdamYLiang/toobU#3]
`videos`
- [x] Hold a reference to the `comments` of a `video`
- [x] Number of `likes` / `dislikes`
---
`users`
- [x] `likedVideoIds` should only exist for the current `user` because `users` shouldn't be able to see what `videos` other `users` liked besides their own (same for `likedCommentIds`)
- [x] Hold a reference to subscribed `channels` for the current `user`
- [x] Don't need `authoredCommentIds` unless making a page/feature that will exclusively show the `comments` for a single `user`
---
`channels`
- [x] Number of `subscriptions`
- [x] Hold a reference to the `videos` for a `channel`
---
`comments`
- [x] Number of `likes` / `dislikes`
---
`playlists`
- [x] Hold a reference to the `videos` on a `playlist`
---
Nice job!

**Comment by AdamYLiang** [comment]
Fixes are done! Let me know if any further improvements can be made, thanks!

**Comment by ssoonmi** [comment]
Awesome job!!
