### ISSUE TITLE
User Auth Review I

### ISSUE THREAD

**Issue by ssoonmi** [AdamYLiang/toobU#5]
#### Sign In Page
- [x] `create account` should be aligned with the start of the input
- [x] `sign in` button should be aligned with the end of the input
- [x] bonus: try to center the form on the page and disable scrolling
---
#### Profile Button on Nav Bar
- [x] style dropdown to look like YouTube's dropdown
- [x] profile button should be circular
- [x] the right of the dropdown should be more aligned with the right of the profile button
- [x] whenever I click on the dropdown besides the sign out, the dropdown closes. Dropdown should only close when user clicks outside of it
---
Nav Bar
- [x] padding on the sides of the nav bar seem a little too small compared to YouTube's
- [x] Your `Log In` link doesn't match YouTube's `SIGN IN` link

**Comment by AdamYLiang** [comment]
Hey Soon-Mi, I fixed most of the issues! As for the two unchecked I have some thoughts on them so when you're free could we discuss them? Thanks!

**Comment by AdamYLiang** [comment]
OK fixed the remaining issues! Let me know if there are any more improvements to be made, thanks!
