### ISSUE TITLE
User Auth Review II

### ISSUE THREAD

**Issue by ssoonmi** [AdamYLiang/toobU#6]
- [x] padding on the right of the navbar still seems to be a little off
- [x] `SIGN IN` Button on the navbar seems a little too big
- [x] `Create account` link on the Sign in form seems a little too big
- [x] Logging in as a demo user should exist on the Sign up form also
- [x] `Demo user` button seems a little off. I suggest changing it in some way (position/styling) to make it look like it flows with the form better instead of looking it was just added in as an afterthought

**Comment by AdamYLiang** [comment]
All done! Let me know if the demo user button is an OK fix and if there's anything else. Thanks!

**Comment by ssoonmi** [comment]
Love it! Good job! You're User Auth feature looks great!
