### ISSUE TITLE
Channels Review I

### ISSUE THREAD

**Issue by ssoonmi** [AdamYLiang/toobU#7]
Create Channel Form
- [x] `Cancel` button should have a cursor pointer
- [x] should disable the create channel button when form is submitted
---
Channel Show
- [x] I shouldn't be able to customize the channel if I'm not the current user
- [x] the channel icon should not have a cursor pointer
- [x] Nav Links on the different tabs should be styled like YouTube's

**Comment by AdamYLiang** [comment]
Issues should be fixed!
